apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: stream-processor-scaler
  namespace: tsoc
spec:
  scaleTargetRef:
    name: tsoc-stream-processor
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: soc-redpanda-cluster.prod.svc.cluster.local:9092
      consumerGroup: tsoc-stream-processor
      topic: raw_traffic
      lagThreshold: "1000"
