apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tsoc-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.tsoc.local
    secretName: tsoc-api-tls
  rules:
  - host: api.tsoc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tsoc-api-service
            port:
              number: 80
