apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-stream-processor
  namespace: tsoc
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: tsoc-stream-processor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-api
  namespace: tsoc
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: tsoc-api
