apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tsoc-api-monitor
  namespace: tsoc
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tsoc-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
